# Generated by Django 3.2 on 2021-04-27 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Актёр')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Актрёр',
                'verbose_name_plural': 'Актёры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Автор отзыва')),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MovieShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Кадры фильма')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Кадр из фильма',
                'verbose_name_plural': 'Кадры фильма',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, verbose_name='Рейтинг фильма')),
            ],
            options={
                'verbose_name': 'Рейтинг фильма',
                'verbose_name_plural': 'Рейтинг фильмов',
                'ordering': ['stars'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Режисёр')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст')),
                ('description', models.TextField(blank=True, verbose_name='Биография')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Коллектив',
                'verbose_name_plural': 'Коллектив',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StarsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_rating', models.IntegerField(blank=True, verbose_name='Рейтинг актёра')),
            ],
            options={
                'verbose_name': 'Рейтинг актёра',
                'verbose_name_plural': 'Рейтинг актёров',
                'ordering': ['stars_rating'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Наименование')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Слоган')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Постер')),
                ('year', models.DateField(blank=True, verbose_name='Год выпуска')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна создания')),
                ('world_premiere', models.CharField(blank=True, max_length=255, verbose_name='Примеьра в мире')),
                ('budget', models.CharField(blank=True, max_length=255, verbose_name='Бюджет')),
                ('fees_USA', models.CharField(blank=True, max_length=255, verbose_name='Сборы в сша')),
                ('fees_world', models.CharField(blank=True, max_length=255, verbose_name='Сборы в мире')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Ссылка')),
                ('actors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.actors', verbose_name='Актеры')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.category', verbose_name='Категория')),
                ('feedback', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.feedback', verbose_name='Отзывы')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.genre', verbose_name='Жанры')),
                ('movie_shots', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.movieshots', verbose_name='Кадры из фильма')),
                ('rating', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.rating', verbose_name='Рейтинг')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.staff', verbose_name='Коллектив')),
                ('stars_rating', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.starsrating', verbose_name='Рейтинг звезд')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='actors',
            name='stars_rating',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Movie.starsrating', verbose_name='Рейтинг актёра'),
        ),
    ]
